export default function Home() {
  return (
    <main className="min-h-screen bg-[#0d1117] text-[#c9d1d9]">
      {/* Hero */}
      <section className="max-w-3xl mx-auto px-6 pt-24 pb-20 text-center">
        <span className="inline-block mb-4 px-3 py-1 rounded-full bg-[#161b22] border border-[#30363d] text-[#58a6ff] text-xs font-medium tracking-wide uppercase">
          Changelog Automation
        </span>
        <h1 className="text-4xl sm:text-5xl font-bold text-white leading-tight mb-5">
          Generate Release Notes from{" "}
          <span className="text-[#58a6ff]">GitHub Commits</span>
        </h1>
        <p className="text-lg text-[#8b949e] mb-8 max-w-xl mx-auto">
          Connect your GitHub repo, let AI analyze your commits and PRs, and get polished release notes in seconds — ready to copy or auto-publish.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <a
            href={process.env.NEXT_PUBLIC_LS_CHECKOUT_URL || "#"}
            className="inline-block px-7 py-3 rounded-lg bg-[#58a6ff] text-[#0d1117] font-semibold text-base hover:bg-[#79b8ff] transition-colors"
          >
            Get Started — $19/mo
          </a>
          <a
            href="#faq"
            className="inline-block px-7 py-3 rounded-lg border border-[#30363d] text-[#c9d1d9] font-semibold text-base hover:border-[#58a6ff] hover:text-[#58a6ff] transition-colors"
          >
            Learn More
          </a>
        </div>
        <div className="mt-14 rounded-xl border border-[#30363d] bg-[#161b22] p-6 text-left font-mono text-sm text-[#8b949e] shadow-xl">
          <div className="mb-2 flex gap-2">
            <span className="w-3 h-3 rounded-full bg-[#ff5f57] inline-block"></span>
            <span className="w-3 h-3 rounded-full bg-[#febc2e] inline-block"></span>
            <span className="w-3 h-3 rounded-full bg-[#28c840] inline-block"></span>
          </div>
          <p className="text-[#58a6ff]">## v2.4.0 — 2025-06-10</p>
          <p className="mt-2"><span className="text-[#3fb950]">### Features</span></p>
          <p>- Add dark mode support across all dashboard views</p>
          <p>- Introduce webhook-based auto-publish to GitHub Releases</p>
          <p className="mt-2"><span className="text-[#f78166]">### Bug Fixes</span></p>
          <p>- Fix pagination on commit history for large repos</p>
          <p className="text-[#8b949e] mt-2 text-xs italic">✦ Generated by ReleaseAI in 3 seconds</p>
        </div>
      </section>

      {/* Pricing */}
      <section className="max-w-md mx-auto px-6 pb-20">
        <h2 className="text-2xl font-bold text-white text-center mb-8">Simple Pricing</h2>
        <div className="rounded-xl border border-[#58a6ff] bg-[#161b22] p-8 text-center shadow-lg">
          <p className="text-[#58a6ff] font-semibold text-sm uppercase tracking-wide mb-2">Pro</p>
          <p className="text-5xl font-bold text-white mb-1">$19</p>
          <p className="text-[#8b949e] text-sm mb-6">per month</p>
          <ul className="text-left space-y-3 mb-8 text-sm">
            {[
              "Unlimited repositories",
              "AI-generated changelogs via OpenAI",
              "GitHub OAuth integration",
              "One-click publish to GitHub Releases",
              "Custom release note templates",
              "Priority support"
            ].map((f) => (
              <li key={f} className="flex items-center gap-2">
                <span className="text-[#3fb950] font-bold">✓</span>
                <span>{f}</span>
              </li>
            ))}
          </ul>
          <a
            href={process.env.NEXT_PUBLIC_LS_CHECKOUT_URL || "#"}
            className="block w-full py-3 rounded-lg bg-[#58a6ff] text-[#0d1117] font-semibold text-base hover:bg-[#79b8ff] transition-colors"
          >
            Start Free Trial
          </a>
          <p className="text-[#8b949e] text-xs mt-3">Cancel anytime. No credit card required for trial.</p>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="max-w-2xl mx-auto px-6 pb-24">
        <h2 className="text-2xl font-bold text-white text-center mb-8">FAQ</h2>
        <div className="space-y-6">
          <div className="border border-[#30363d] rounded-lg p-5 bg-[#161b22]">
            <h3 className="font-semibold text-white mb-2">How does ReleaseAI connect to GitHub?</h3>
            <p className="text-[#8b949e] text-sm">You authenticate via GitHub OAuth. We request read access to your repositories and pull request data — we never write to your code.</p>
          </div>
          <div className="border border-[#30363d] rounded-lg p-5 bg-[#161b22]">
            <h3 className="font-semibold text-white mb-2">What AI model powers the changelog generation?</h3>
            <p className="text-[#8b949e] text-sm">We use OpenAI GPT-4o to analyze commit messages, PR titles, and descriptions, then produce structured, human-readable release notes.</p>
          </div>
          <div className="border border-[#30363d] rounded-lg p-5 bg-[#161b22]">
            <h3 className="font-semibold text-white mb-2">Can I customize the format of the release notes?</h3>
            <p className="text-[#8b949e] text-sm">Yes. Pro users can define custom templates — choose sections, tone, grouping by label, and output format (Markdown, HTML, or plain text).</p>
          </div>
        </div>
      </section>

      <footer className="border-t border-[#21262d] py-8 text-center text-[#8b949e] text-sm">
        <p>© {new Date().getFullYear()} ReleaseAI. All rights reserved.</p>
      </footer>
    </main>
  );
}
